### PR TITLE
updates spacing between links to 20px and fix mobile issues

### PR DESCRIPTION
**Pull request by DilwoarH**
Ticket: https://trello.com/c/hRqh57Xn/531-navigation-header-should-have-padding-between-links-and-fix-mobile-styles

Required changes before merging this: https://github.com/alphagov/govuk_publishing_components/pull/691

### Desktop

screen shot 2018-12-20 at 10 28 51

### Mobile

screen shot 2018-12-20 at 10 29 04

### Mobile with expanded navigation

screen shot 2019-01-02 at 16 39 52

### CODE REVIEW

**Comment by alex-ju** [comment]
Hmm.. 🤔 the way I understand this card is that on mobile we expect the secondary navigation items to be available in the collapsible main navigation menu. It's worth clarifying this with @soniaturcotte, but that's how I get it.

**Comment by soniaturcotte** [comment]
> Hmm.. 🤔 the way I understand this card is that on mobile we expect the secondary navigation items to be available in the collapsible main navigation menu – instead of not displaying them at all.
> It's worth clarifying this with @soniaturcotte, but that's how I get it.

Yes that’s right, we shouldn’t remove them for mobile users. If users are accessing the app from mobile, there is a greater chance that they are in some kind of crisis or urgency and the support links are especially important in that case. 

The designs for the mobile view are here: https://trello.com/c/hamBfSS0/307-navigation-header-including-options-to-provide-feedback

**Comment by DilwoarH** [comment]
@alex-ju @soniaturcotte - thanks for letting me know

**Comment by DilwoarH** [comment]
Required PR: https://github.com/alphagov/govuk_publishing_components/pull/691

**Comment by soniaturcotte** [comment]
This is wonderful ✨

**Pull request merged**
