### PR TITLE
Add release note for topic search

### PR DESCRIPTION
**Pull request by alex-ju**
[Trello card](https://trello.com/c/RFcetKNF)

### CODE REVIEW

**Comment by kevindew** [comment]
Thanks @alex-ju - this PR should also cover removing the feature flag.

**Comment by alex-ju** [comment]
Yep. Looking back there were separate PRs, but I think it makes more sense for this to be done at once. Not sure if analytics is a blocker for this though.

**Comment by kevindew** [comment]
@alex-ju Yup - I think we'll chat to Tobi about that this afternoon.

**Comment by alex-ju** [comment]
🙌Thanks Emma! Bumped the date to 24 too, then I saw your push. I'll wait for the CI then I'll get it merged.

**Pull request merged**
