### PR TITLE
Brakeman now runs automatically for Rails apps

### PR DESCRIPTION
**Pull request by erino**
As per https://github.com/alphagov/govuk-jenkinslib/pull/19

### CODE REVIEW

**Comment by erino** [comment]
@benthorner Isn't the current behaviour that brakeman doesn't run locally? as it's not included in the Gemfile?

**Comment by benthorner** [comment]
@erino Yes, but that's not optimal as it means we can't debug brakeman errors without manually setting it up locally - it should really be part of the local development environment, like the linting is. I'm suggesting that we add it to the Gemfile and ensure it runs after the linting, so we're not dependent on CI for debugging output.

**Comment by erino** [comment]
@benthorner Cool, just checking that I wasn't missing anything

**Comment by benthorner** [comment]
@erino 👍 but also need to change the `Rakefile`.

**Comment by benthorner** [comment]
End of Friday PR cleanout ;-).

**Comment by erino** [comment]
thanks for merging!

**Pull request merged**
