### PR TITLE
Fix failing tests due to bad translation key

### PR DESCRIPTION
**Pull request by benthorner**

### CODE REVIEW

**Comment by benthorner** [comment]
It did raise errors - the test failed. May have been caused by a branch not re-running tests after a non-conflicting change on master.

**Comment by tijmenb** [comment]
@benthorner which PR introduced this change?

**Comment by benthorner** [comment]
I think it was a combination of a5aef16b and cf8cc160.

**Comment by kevindew** [comment]
I didn't know about `I18n.t!` raising errors that does seem a good option.

**Comment by kevindew** [comment]
Looks like we could also do it through a config variable `config.action_view.raise_on_missing_translations = true` https://stackoverflow.com/questions/8066901/rails-how-to-raise-i18n-translation-is-missing-exceptions-in-the-testing-enviro

**Comment by benthorner** [comment]
We already have this in `config/application.rb` - as now documented in the ADR ;-).

**Pull request merged**
