### PR TITLE
Handle no Publishing API for organisation filters

### PR DESCRIPTION
**Pull request by benthorner**
https://trello.com/c/GsK9GgOu/241-filter-index-page-by-organisation

### CODE REVIEW

**Comment by kevindew** [comment]
Thanks for picking this up so promptly. Code looks good although I wonder if it makes more sense from a UX angle to not have a field at all rather than one that is empty?

**Comment by benthorner** [comment]
@kevindew I tried that - unfortunately this causes a failure because it's required in order to select nothing!

**Comment by benthorner** [comment]
@kevindew I see what you mean, although I think this makes it easier to see there's something wrong, rather than mysteriously removing the feature.

**Comment by kevindew** [comment]
@benthorner ah what fails?

**Pull request merged**
