### PR TITLE
Enable email links in markdown toolbar

### PR DESCRIPTION
**Pull request by alex-ju**
This PR:
- updates markdown-toolbar-element to [0.2.0](https://github.com/alphagov/markdown-toolbar-element/pull/9) which updates the link button to render email markdown when the selected text matches a basic email pattern (name@domain.tld).
- removes email guidance from sidebar

Demo: https://content-publisher-revi-pr-1035.herokuapp.com/component-guide/markdown_editor/default/preview

[Trello card](https://trello.com/c/W1EYHDBn)

### CODE REVIEW

**Comment by soniaturcotte** [comment]
> Yay to kill a vendored asset 👍
> 
> Looks good to me, have you checked with @benhazell or @soniaturcotte that they're expecting the email guidance to be removed?

Yes it's part of the acceptance criteria. We want to remove all that guidance eventually.

**Comment by benhazell** [comment]
> Yay to kill a vendored asset 👍
> 
> Looks good to me, have you checked with @benhazell or @soniaturcotte that they're expecting the email guidance to be removed?

I haven't had a chance to try the new functionality out and form a view on if we should cut the email guidance right away. Is it on Integration now for me to look at?
If in doubt I'd leave the guidance there for the moment, it doesn't hurt.

**Comment by kevindew** [comment]
You can view it on heroku: https://content-publisher-revi-pr-1035.herokuapp.com/documents/8650320d-f0cc-4f95-bf7a-99869822728e:en/edit

**Comment by benhazell** [comment]
> You can view it on heroku: https://content-publisher-revi-pr-1035.herokuapp.com/documents/8650320d-f0cc-4f95-bf7a-99869822728e:en/edit

Thanks. This is fine. We'll see how people understand it when there is no specific reference to emails in the interface - it's being tested next week.

**Pull request merged**
