### PR TITLE
Add page info to pagination links

### PR DESCRIPTION
**Pull request by 1pretz1**
The page information was missed on the first pass of implementing the pagination
feature, I believe because the prototype was out of date. Now the
pagination links display information around what page is currently being
displayed.

This comes after a product review from @Tobiogunsina.

## Before
Screenshot 2020-01-15 at 11 54 04
Screenshot 2020-01-15 at 11 54 10

## After 
Screenshot 2020-01-15 at 11 42 13
Screenshot 2020-01-15 at 13 08 28

Trello:
https://trello.com/c/TsRTLbiW/1276-move-document-history-from-tab-to-secondary-navigation-and-add-pagination

### CODE REVIEW

**Comment by kevindew** [comment]
Have only quickly scanned this PR so haven't seen the code. But the screenshot in after looks wrong to have both page 2 as the previous and next page.

**Comment by 1pretz1** [comment]
That's how the index page currently displays the page information @kevindew, shall I change them both to display the actual previous and next page, so for example 1 (previous page) and 3 (next page) for page two ?

**Comment by kevindew** [comment]
> That's how the index page currently displays the page information @kevindew, shall I change them both to display the actual previous and next page, so for example 1 (previous page) and 3 (next page) for page two ?

Yup that might well be the bug @JonathanHallam found today - so worth checking if he's also fixing it.

**Comment by 1pretz1** [comment]
Updated @kevindew

**Pull request merged**
